"""
vki_config.py - configuration for the VKI-LS59 experiments
(FNO / RNO / DNO / RNO_D).

Follows the FoundNO config pattern (see airfoil_config.py): an aggregator
VkiDefault with model / data / opt / loss subsections, overridable from the
command line via dotted keys (--model.n_modes, --data.batch_size, ...).
"""

from typing import List, Literal

from zencfg import ConfigBase

from fnofound.data.config.opt import OptimizationConfig

CaseType = Literal['raw', 'square']


class VkiModelConfig(ConfigBase):
    """Shared model hyperparameters.

    Per-case channel layout (overridden by the registry in vki_train.py):
      raw    (FNO/RNO on the structured 301x121 C-grid) and
      square (DNO/RNO_D on the 128x128 universal square)
    both use in=5: (x, y, sdf) + the scalar conditions (angle_in, mach_out)
    broadcast by the dataset as constant channels; out=6: mach, nut, ro,
    roe, rou, rov. DNO additionally gets grid_mesh (physical x, y).
    """
    n_modes: List[int] = [8, 8]
    hidden_channels: int = 64
    n_layers: int = 5
    in_channels: int = 5
    out_channels: int = 6
    use_grid: bool = True
    padding: int = 0
    use_geom: bool = True          # DNO only: c(grid_mesh) terms in every layer


class VkiDataConfig(ConfigBase):
    """Data paths and loading settings (external drive, not committed)."""
    case_type: CaseType = 'square'
    # Root with the per-case subfolders (as in airfoil_config):
    #   square: {root_dir}/DNO_dataset   (npy, generated by prep_square.py)
    #   raw:    {plaid_dir}              (original PLAID dataset + split.json)
    root_dir: str = '/media/expiwt/f2d8c27a-bdac-4400-b1be-cdb75b6b5a40/3sem/hugging_face/VKI-LS59'
    plaid_dir: str = '/media/expiwt/f2d8c27a-bdac-4400-b1be-cdb75b6b5a40/hugging_face/VKI-LS59/plaid_dataset'
    batch_size: int = 4
    num_workers: int = 2
    cache: bool = False            # preload raw/split data into RAM


class VkiLossConfig(ConfigBase):
    """FieldLpLoss settings (physical space, no normalization)."""
    # All six channels, nut included (same decision as the airfoils fl4 setup).
    field_indices: List[int] = [0, 1, 2, 3, 4, 5]
    weights: List[float] = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


class VkiOptConfig(OptimizationConfig):
    """Optimization settings."""
    n_epochs: int = 100
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    scheduler: str = 'StepLR'
    step_size: int = 60
    gamma: float = 0.98


class VkiDefault(ConfigBase):
    """Complete VKI-LS59 experiment configuration."""
    verbose: bool = True
    arch: str = 'vki'

    model: VkiModelConfig = VkiModelConfig()
    data: VkiDataConfig = VkiDataConfig()
    opt: VkiOptConfig = VkiOptConfig()
    loss: VkiLossConfig = VkiLossConfig()
